#!/usr/bin/env python3
"""Generate compositions/ - pre-assembled page shells - from the recipes.

Usage:
  python ci/compose.py            regenerate compositions/
  python ci/compose.py --check    fail if compositions/ differs from what this
                                  script would generate (CI runs this)

A composition is a recipe from ci/page-recipes.json promoted to a deliverable:
one folder holding a complete page.html with its copy slots still open, the
page.css a build would otherwise concatenate by hand, a manifest naming the
exact pattern versions inside, and a generated README. An agent building a
standard page fetches one folder instead of nine pattern folders.

Which recipes ship is decided in ci/page-recipes.json - a recipe carrying a
`composition` block ships, the rest stay validation fixtures - so the fixture
that must stay valid and the shell agents fetch are the same pattern list and
cannot drift apart. Everything under compositions/ comes out of this script;
nothing there is ever hand-edited. The freshness check mirrors the one
ci/lint.py runs on INDEX.md.

The library tag is stamped into manifest.json and nowhere else, so a release
rewrites one file per composition rather than all of them.

Exit codes: 0 = clean. 1 = a composed page fails its page-level checks, or
--check found committed output stale. 2 = a composition cannot be built at
all - an unknown pattern, a slot with no sample, a name collision, or
generated text the comment policy refuses.
"""
import argparse
import json
import re
import shutil
import sys
import textwrap
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "compositions"
RECIPES = ROOT / "ci" / "page-recipes.json"

from check_page import (                                    # noqa: E402
    PATTERNS, apply_variants, axes_of, check_avoid_with, check_deprecated,
    check_ground_run, check_headings, check_known_page_type,
    check_one_per_page, check_opener_reserves_room, check_variant_choice,
    load, parse_recipe,
)
# The banners this script writes are shipped HTML comments, so they are held
# to the same comment policy lint.py holds pattern comments to. lint never
# scans compositions/ - the scan happens here instead, at the moment the text
# is generated, where the fix is one file away.
from lint import (                                           # noqa: E402
    BANNED_COMMENT_PATTERNS, BANNED_COMMENT_TERMS,
    description_vocabulary_faults,
)

GENERATED_BY = "ci/compose.py - regenerate with: python ci/compose.py; never hand-edit"

FURNITURE = re.compile(r"\{\{[^{}]+\}\}")
COMMENT = re.compile(r"<!--(.*?)-->", re.S)
SLOT_INNER = re.compile(r"^\s*slot\s*:\s*[\w-]+\s*$")

RULE = "=" * 64

# The head a served page needs. Every {{ }} value is a platform furniture
# token from the table in TOKENS.md, kept verbatim for the platform to fill -
# the same head scaffold ci/build_preview.py and ci/check_page.py write, with
# the preview-only stand-ins replaced by the real tokens.
PAGE = """<!-- {rule}
     {name}@{version} - generated by ci/compose.py from ci/page-recipes.json.
     Never hand-edit: change the pattern or the recipe and regenerate
     with `python ci/compose.py`.

     How to use this shell:
       1. Write real copy into every slot. A content slot is an HTML comment,
          `slot: name`; an attribute slot is a literal `slot:name` value.
       2. Duplicate whatever block a pattern's own comments say to duplicate,
          one per real item - never invent content to fill a block.
       3. Strip every comment, this one included, in the same pass. A
          finished page contains no comment and no `slot:` anywhere.
       4. Keep every {{{{ }}}} token exactly as it stands, head and body: the
          platform fills them per brand and per page.
       5. page.css beside this file is the page's whole stylesheet beyond
          the brand's tokens - load it after the brand's own stylesheet,
          or merge it into the brand stylesheet unchanged.
     {rule} -->
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{{{pageTitle}}}}</title>
<meta name="description" content="{{{{metaDescription}}}}">
<meta name="keywords" content="{{{{metaKeywords}}}}">
<link rel="canonical" href="{{{{canonicalPage}}}}">
<link rel="icon" href="{{{{favicon}}}}">
<link rel="stylesheet" href="page.css">
</head>
<body>
{markup}
</body>
</html>
"""


def die(message):
    print(message)
    raise SystemExit(2)


def strip_tags(text):
    return re.sub(r"<[^>]+>", " ", text)


# A pattern-README reference, tolerant of the line wrap README prose often
# lands on: "the\nREADME" is the same reference as "the README".
README_REF = re.compile(r"the\s+README\b")

# Phrases true of a pattern alone and unanswerable in a shell. Currently
# empty: cta-band's "before the footer" placement note used to be dropped
# here on the theory that a page carries no footer markup, and that theory
# did not survive measurement - served canvas pages are the stored document
# with tokens hydrated, nothing injected - so every shell now ends with
# the colophon pattern and the note is simply true.
PHRASE_REWRITES = []


def comment_safe(text):
    """Text destined for the inside of an HTML comment. Only the exact
    closing sequence can end the comment early, so only it is spaced apart -
    a bare double hyphen stays, or spacing it would corrupt any sample class
    carrying one."""
    return text.replace("-->", "-- >")


def check_banner_policy(where, texts, described=()):
    """The comment policy from lint.py, applied to generated comment text.

    Two rules, because a banner has two authors. What this script WRITES is
    held to the full comment policy. What it COPIES out of a pattern's own
    `description` and `needs` is held to lint.py's rule for those two fields
    instead - deliberately the looser one. Those fields describe what a
    pattern is for in the vocabulary of the thing being built, and lint
    already rules on which ordinary domain words survive there; holding a
    copy of them to the stricter rule would make a pattern shippable on its
    own and unshippable inside a shell over the same words. `source-note` is
    the case that shows it: its whole subject is who measured a figure.
    """
    for text in texts:
        low = text.lower()
        for term in BANNED_COMMENT_TERMS:
            if re.search(rf"(?<!\w){re.escape(term.strip())}(?!\w)", low):
                die(f"{where}: banner-policy: generated comment says "
                    f"'{term.strip()}' - shipped comments follow the comment "
                    f"policy in ci/lint.py")
        for pattern, why in BANNED_COMMENT_PATTERNS:
            if re.search(pattern, low):
                die(f"{where}: banner-policy: {why}")
    for text in described:
        for fault in description_vocabulary_faults(text):
            die(f"{where}: banner-policy: a pattern's description or needs "
                f"{fault}")


def find_slots(body):
    """Every slot in the markup, in document order, each named once."""
    found = []
    for m in re.finditer(r'([\w-]+)="slot:([\w-]+)"|<!--\s*slot\s*:\s*([\w-]+)\s*-->',
                         body):
        attr, attr_key, comment_key = m.groups()
        key = attr_key or comment_key
        entry = next((e for e in found if e["key"] == key), None)
        if entry is None:
            found.append({"key": key, "attrs": []})
            entry = found[-1]
        if attr:
            entry["attrs"].append(attr)
    return found


def pattern_names():
    return sorted(p.name for p in PATTERNS.iterdir() if p.is_dir())


def patterns_in_markup(value):
    """Pattern names whose classes a markup sample carries.

    Library convention: a pattern's selectors reference its own classes, and
    those classes are the pattern's name or the name plus a suffix. A slot
    whose sample is another pattern's markup - hero-stated's assurance slot
    carries cta-assurance - is an instruction to use that pattern, so its CSS
    has to travel with the shell or following the instruction ships an
    unstyled list.
    """
    classes = set()
    for m in re.finditer(r'class="([^"]+)"', value):
        classes.update(m.group(1).split())
    return [n for n in pattern_names()
            if any(c == n or c.startswith(n + "-") for c in classes)]


def slot_guidance(slot, sample):
    """What goes in the slot and roughly how long, from the pattern's own
    preview sample - fake by design, but its shape and length are the shape
    and length the pattern was drawn for. Returns (summary, sample_lines):
    the one-line summary, and for markup slots the sample itself, so nothing
    about filling the slot requires fetching preview-content.json."""
    key, attrs = slot["key"], slot["attrs"]
    value = str(sample.get(key, ""))
    if attrs:
        where = "/".join(sorted(set(attrs)))
        if "src" in attrs:
            hint = ("a path to real material, or a lib/placeholders/ stand-in "
                    "while the brand's photography is still coming - said out "
                    "loud, never silently")
        elif "alt" in attrs:
            hint = "what the image shows, in words"
        elif "id" in attrs or "aria-labelledby" in attrs:
            hint = "a page-unique id drawn from the heading"
        else:
            hint = "a short label, about %d word(s)" % max(len(value.split()), 1)
        return f"attribute ({where}): {hint}", []
    if value.lstrip().startswith("<"):
        words = len(strip_tags(value).split())
        uses = patterns_in_markup(value)
        carried = ("; uses " + " and ".join(uses) + ", whose CSS is in page.css"
                   if uses else "")
        # Never break inside a word or at a hyphen: the sample is markup,
        # and a class name split across lines misleads more than a long
        # line does.
        return (f"markup, about {words} words of copy{carried}",
                textwrap.wrap(comment_safe(value), width=58,
                              break_long_words=False, break_on_hyphens=False))
    words = len(value.split())
    shown = value if len(value) <= 58 else value[:55] + "..."
    return f"text, about {words} word(s). Sample: {shown}", []


def section_banner(item, mods, position, total):
    """The generated preface to one pattern's verbatim markup.

    Returns (banner, written, copied): the comment itself, the part this
    script composes, and the part lifted out of the pattern's `description`
    and `needs`. The two are returned apart because check_banner_policy holds
    them to different rules - see its docstring.
    """
    meta, sample = item["meta"], item["sample"]
    lines = [f"section {position} of {total} : {item['name']} v{meta.get('version', '?')}"]
    if mods:
        lines.append("variant: " + ", ".join(f"{k}={v}" for k, v in mods.items()))
    head = len(lines)
    copied = meta.get("description", "")
    lines += textwrap.wrap(copied, width=64)
    needs = meta.get("needs", "").strip()
    if needs and needs.lower() != "none":
        copied += " " + needs
        lines += textwrap.wrap("needs: " + needs, width=64)
    tail_from = len(lines)
    lines.append("slots:")
    for slot in find_slots(item["body"]):
        summary, sample_lines = slot_guidance(slot, sample)
        note = "; shape it like this sample:" if sample_lines else ""
        lines.append(f"  {slot['key']:<18} {summary}{note}")
        lines += [f"  {'':<18} {sample_line}" for sample_line in sample_lines]
    inner = "\n".join(f"     {line}".rstrip() for line in lines)
    banner = f"<!-- {RULE}\n{inner}\n     {RULE} -->"
    written = "\n".join(lines[:head] + lines[tail_from:])
    return banner, written, copied


class AmbiguousDrop(Exception):
    """Dropping these lines would truncate a sentence."""


def drop_variant_lines(inner, rungs):
    """Remove the comment lines that instruct a variant choice.

    A line is doomed when it names a variant rung or the word modifier. The
    doomed lines are removed in contiguous blocks, and a block may only go
    where the removal cannot truncate a sentence: the kept text before it
    must end a sentence (or be empty), and the kept text after it must open
    one (or be empty). Anything else raises rather than shipping half a
    sentence - the fix is rewording the pattern's comment, not a cleverer
    truncation here.

    A pattern that declares no variant axes has no variant instruction to
    drop, and nothing is taken from one. There the word `modifier` can only
    name a fixed class the shell still ships and the builder still has to act
    on - feature-panels' three ranked grounds, comparison-table's recommended
    column - and removing those would take real instruction out of the shell
    on the strength of one word.
    """
    if not rungs:
        return inner
    lines = inner.split("\n")
    doomed = {i for i, ln in enumerate(lines)
              if "modifier" in ln or any(r in ln for r in rungs)}
    if not doomed:
        return inner
    for i in sorted(doomed):
        if i - 1 in doomed:
            continue                                # not the block's start
        end = i
        while end + 1 in doomed:
            end += 1
        before = "\n".join(lines[j] for j in range(i) if j not in doomed).strip()
        after = "\n".join(lines[j] for j in range(end + 1, len(lines))
                          if j not in doomed).strip()
        if before and before[-1] not in ".!?:":
            raise AmbiguousDrop(f"the text before {lines[i].strip()!r} does "
                                f"not end a sentence")
        opener = re.search(r"[A-Za-z]", after)
        if after and not (opener and opener.group(0).isupper()):
            raise AmbiguousDrop(f"the text after {lines[end].strip()!r} does "
                                f"not open a sentence")
    return "\n".join(ln for j, ln in enumerate(lines) if j not in doomed)


def _prove_drop_safety():
    """The three branches of drop_variant_lines, exercised on every run: a
    clean drop lands, a drop that would truncate a sentence is refused, and a
    pattern with no axes keeps every word."""
    clean = drop_variant_lines(" Take one ground modifier.\n Keep this. ",
                               {"--deep"})
    assert "Keep this." in clean and "modifier" not in clean
    try:
        drop_variant_lines(" This sentence names the --deep rung\n"
                           " and carries on past it. ", {"--deep"})
    except AmbiguousDrop:
        pass
    else:
        raise AssertionError("a mid-sentence drop was not refused")
    axeless = " Each panel carries one ground modifier\n and they are ranked. "
    assert drop_variant_lines(axeless, set()) == axeless


def rewrite_comments(name, meta, body):
    """Builder comments travel with the markup, and some go stale in a
    shell. 'the README' - however the line wraps - means the pattern's own
    README, which is not in this folder: point at it by path. A variant
    instruction offers a choice the recipe has already made and the banner
    already states: drop it, whole sentences only. A phrase about page
    furniture the shell cannot vouch for is reworded from the table above.
    A comment with nothing left in it goes entirely."""
    rungs = {f"--{v}" for values in axes_of(meta).values() for v in values}

    def fix(m):
        inner = m.group(1)
        if SLOT_INNER.match(inner):
            return m.group(0)
        inner = README_REF.sub(f"patterns/{name}/README.md", inner)
        for phrase, said in PHRASE_REWRITES:
            inner = phrase.sub(said, inner)
        try:
            inner = drop_variant_lines(inner, rungs)
        except AmbiguousDrop as why:
            die(f"{name}: variant instruction cannot be dropped cleanly "
                f"({why}) - reword the pattern's comment")
        lines = inner.split("\n")
        if not any(ln.strip() for ln in lines):
            return ""
        lines[0] = " " + lines[0].lstrip() if lines[0].strip() else lines[0]
        return "<!--" + "\n".join(lines) + "-->"

    body = COMMENT.sub(fix, body)
    return re.sub(r"\n{3,}", "\n\n", body)


def compose_body(item, mods):
    """The pattern's markup verbatim, less its metadata header, on the
    variant the recipe chose, with the stale-in-a-shell comments rewritten.
    The remaining builder comments stay: they carry the duplicate-this-block
    instructions, and the consumer strips every comment in the pass that
    fills the slots, exactly as with a pattern fetched on its own."""
    body = re.sub(r"\s*<!--\n.*?\n-->", "", item["html"], count=1, flags=re.S)
    body = apply_variants(item["name"], item["meta"], body.strip(), mods)
    return rewrite_comments(item["name"], item["meta"], body)


def pattern_css(item):
    """The pattern's CSS, with the one reference that goes stale in a shell
    pointed at its real target: 'the README' in a pattern.css comment -
    however the line wraps - means the pattern's own README, which is not
    the README in this folder."""
    return README_REF.sub(f"patterns/{item['name']}/README.md",
                          item["css"].strip())


def page_checks(page, chosen, page_type):
    """The same page-level checks ci/check_page.py runs on a recipe."""
    failures = []
    for found in (
        check_known_page_type(page, page_type),
        check_deprecated(page),
        check_one_per_page(page),
        check_avoid_with(page),
        check_variant_choice(page, chosen),
        check_opener_reserves_room(page),
        check_headings(page),
    ):
        failures += found
    ground_bad, _ = check_ground_run(page, chosen)
    return failures + ground_bad


def slot_support(page):
    """Patterns whose markup a slot sample carries, beyond the page's own.

    Their CSS ships in page.css so the shell's own instructions cannot lead
    to unstyled markup. Returns [(item, for_slot, of_pattern)].
    """
    on_page = {item["name"] for item in page}
    support, seen = [], set()
    for item in page:
        for slot in find_slots(item["body"]):
            value = str(item["sample"].get(slot["key"], ""))
            if not value.lstrip().startswith("<"):
                continue
            for name in patterns_in_markup(value):
                if name in on_page or name in seen:
                    continue
                extra, err = load(name)
                if err:
                    die(f"slot support: {err}")
                support.append((extra, slot["key"], item["name"]))
                seen.add(name)
    return support


def compose_one(recipe, library):
    """One composition's files, as {filename: text}."""
    spec = recipe["composition"]
    name, version = spec["name"], spec["version"]
    where = f"compositions/{name}@{version}"
    parsed, err = parse_recipe(recipe["patterns"])
    if err:
        die(f"{where}: recipe: {err}")

    page, chosen = [], []
    for pattern_name, mods in parsed:
        item, err = load(pattern_name)
        if err:
            die(f"{where}: recipe: {err}")
        item["body"] = compose_body(item, mods)
        # Guidance is derived from the sample, so a slot without one is a
        # slot this script cannot describe - refuse rather than write a
        # shell that says nothing about what goes in it.
        for slot in find_slots(item["body"]):
            if slot["key"] not in item["sample"]:
                die(f"{where}: {item['name']} slot {slot['key']!r} has no "
                    f"sample in preview-content.json")
        page.append(item)
        chosen.append(mods)

    bad = page_checks(page, chosen, recipe["page"])
    if bad:
        for line in bad:
            print(f"{where}: page-check: {line}")
        raise SystemExit(1)

    support = slot_support(page)

    total = len(page)
    sections = []
    css = [f"/* {name}@{version} - generated by ci/compose.py. The patterns' "
           f"CSS in page order. Never hand-edit: change the pattern and "
           f"regenerate. */"]
    banners, copied_texts = [], []
    for position, (item, mods) in enumerate(zip(page, chosen), start=1):
        banner, written, copied = section_banner(item, mods, position, total)
        banners.append(written)
        copied_texts.append(copied)
        sections.append(banner)
        sections.append(item["body"])
        css.append(f"/* ---- {item['name']} v{item['meta'].get('version', '?')} ---- */\n"
                   + pattern_css(item))
    for extra, for_slot, of_pattern in support:
        css.append(f"/* ---- {extra['name']} v{extra['meta'].get('version', '?')} "
                   f"- carried for {of_pattern}'s {for_slot} slot ---- */\n"
                   + pattern_css(extra))

    html = PAGE.format(rule=RULE, name=name, version=version,
                       markup="\n\n".join(sections))

    check_banner_policy(where, banners + [html.split("<!doctype", 1)[0]],
                        described=copied_texts)

    # Every furniture token a pattern carries must reach the shell byte for
    # byte - these render on live sites, and a mangled one renders as text.
    for item in page:
        for token in FURNITURE.findall(item["body"]):
            if token not in html:
                die(f"{where}: furniture token {token} from {item['name']} "
                    f"did not survive assembly")

    manifest = {
        "composition": name,
        "version": version,
        "page": recipe["page"],
        "library": library,
        "generated-by": GENERATED_BY,
        "patterns": [
            {"name": item["name"],
             "version": item["meta"].get("version", ""),
             **({"variant": mods} if mods else {})}
            for item, mods in zip(page, chosen)
        ],
    }
    if support:
        manifest["slot-support"] = [
            {"name": extra["name"],
             "version": extra["meta"].get("version", ""),
             "for-slot": for_slot, "of": of_pattern}
            for extra, for_slot, of_pattern in support
        ]

    readme = compose_readme(recipe, name, version, page, chosen, support)
    return {
        "page.html": html,
        "page.css": "\n\n".join(css) + "\n",
        "manifest.json": json.dumps(manifest, indent=2) + "\n",
        "README.md": readme,
    }


def compose_readme(recipe, name, version, page, chosen, support):
    lines = [
        f"# {name}@{version}",
        "",
        "Generated by `ci/compose.py` from `ci/page-recipes.json` - never "
        "hand-edit; change the source and regenerate.",
        "",
        f"A **{recipe['page']}** page shell. {recipe['why']}",
        "",
        "Fetch `page.html` and `page.css`, write real copy into the slots, "
        "duplicate whatever block a pattern's comments say to duplicate, "
        "strip every comment, and keep each `{{ }}` token exactly as found - "
        "the platform fills those.",
        "",
        "## Wiring",
        "",
        "The brand's stylesheet loads first: link the brand's own "
        "`global.css` - its token values, per [TOKENS.md](../../TOKENS.md) - "
        "ahead of `page.css`, or merge `page.css` into it unchanged. "
        "`page.css` carries only the patterns' rules and reads every colour, "
        "radius and font from the brand's tokens.",
        "",
        "The page carries its own site footer: this shell closes with the "
        "`colophon` pattern, and the platform fills its legal links and "
        "footer menu at serve time - keep every `{{ }}` token in it exactly "
        "as found. A site header is likewise a pattern a page carries "
        "(`masthead-nav` in this library); this composition ships without "
        "one.",
        "",
    ]
    if any("src" in slot["attrs"]
           for item in page for slot in find_slots(item["body"])):
        lines += [
            "This shell needs photography. An image slot takes real material "
            "- or, while the brand's photography is still coming, one of the "
            "library's stand-ins from `lib/placeholders/` (its README has "
            "the shapes and the rules): copied into the brand's own "
            "`site/images/`, named to the partner as a placeholder out loud, "
            "and recorded in the brand log as an image still owed. Never a "
            "placeholder for a person.",
            "",
        ]
    lines += [
        "## Sections, in order",
        "",
    ]
    for position, (item, mods) in enumerate(zip(page, chosen), start=1):
        variant = " (" + ", ".join(f"{k}={v}" for k, v in mods.items()) + ")" if mods else ""
        lines.append(f"{position}. **{item['name']}** "
                     f"v{item['meta'].get('version', '?')}{variant} - "
                     f"{item['meta'].get('description', '')}")
        for slot in find_slots(item["body"]):
            summary, sample_lines = slot_guidance(slot, item["sample"])
            tail = ("; its sample shape is printed in page.html's banner"
                    if sample_lines else "")
            lines.append(f"   - `{slot['key']}` - {summary}{tail}")
    if support:
        lines += [
            "",
            "Also in `page.css`: "
            + "; ".join(f"**{extra['name']}** "
                        f"v{extra['meta'].get('version', '?')}, carried for "
                        f"{of_pattern}'s `{for_slot}` slot"
                        for extra, for_slot, of_pattern in support)
            + ".",
        ]
    lines += [
        "",
        "## What is still yours to decide",
        "",
        "Copy, imagery and brand - never structure. The words in every slot "
        "are the brand's own; images are real material meeting each "
        "pattern's stated needs; the look comes from the brand's token "
        "values ([TOKENS.md](../../TOKENS.md)). The sections, their order "
        "and their markup are the composition - to change those, build from "
        "patterns directly instead.",
        "",
    ]
    return "\n".join(lines)


def compose_index(built):
    lines = [
        "# Compositions",
        "",
        "Pre-assembled page shells - generated by `ci/compose.py` from "
        "`ci/page-recipes.json`, never hand-edited.",
        "Fetch one folder, write real copy into its slots, strip the "
        "comments, done - instead of assembling patterns by hand.",
        "",
    ]
    for folder, recipe in built:
        order = " -> ".join(recipe["patterns"])
        lines.append(f"- **{folder}** - {recipe['page']} - {order} - {recipe['why']}")
    return "\n".join(lines) + "\n"


def generate():
    """Everything under compositions/, as {relative path: text}."""
    _prove_drop_safety()
    recipes = json.loads(RECIPES.read_text(encoding="utf-8"))
    library = (ROOT / "LATEST").read_text(encoding="utf-8").strip()
    shipped = [r for r in recipes["recipes"] if "composition" in r]
    if not shipped:
        die("no recipe carries a composition block; nothing to generate")

    names = [f"{r['composition']['name']}@{r['composition']['version']}" for r in shipped]
    if len(set(names)) != len(names):
        die(f"composition names collide: {sorted(names)}")

    files, built = {}, []
    for recipe in shipped:
        folder = f"{recipe['composition']['name']}@{recipe['composition']['version']}"
        for filename, text in compose_one(recipe, library).items():
            files[f"{folder}/{filename}"] = text
        built.append((folder, recipe))
    files["README.md"] = compose_index(built)
    return files


def main():
    ap = argparse.ArgumentParser(
        description="Generate compositions/ from ci/page-recipes.json.")
    ap.add_argument("--check", action="store_true",
                    help="compare instead of writing; non-zero when stale")
    args = ap.parse_args()

    files = generate()

    if args.check:
        findings = []
        for rel, text in sorted(files.items()):
            path = OUT / rel
            held = path.read_text(encoding="utf-8") if path.is_file() else None
            if held != text:
                findings.append(f"compositions/{rel}: stale-composition: does "
                                f"not match the patterns and recipes; run ci/compose.py")
        if OUT.is_dir():
            for path in sorted(OUT.rglob("*")):
                rel = path.relative_to(OUT).as_posix()
                if path.is_file() and rel not in files:
                    findings.append(f"compositions/{rel}: stray-file: nothing "
                                    f"generates this; run ci/compose.py")
        if findings:
            print("\n".join(findings))
            print(f"\n{len(findings)} finding(s).")
            return 1
        print(f"clean: {len(files)} generated file(s) match compositions/.")
        return 0

    if OUT.exists():
        shutil.rmtree(OUT)
    for rel, text in sorted(files.items()):
        path = OUT / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
    folders = sorted({rel.split("/")[0] for rel in files if "/" in rel})
    print(f"wrote {len(files)} file(s): {', '.join(folders)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
