#!/usr/bin/env python3
"""Generate compositions/ - pre-assembled page shells - from the recipes.

Usage:
  python ci/compose.py            regenerate compositions/
  python ci/compose.py --check    fail if compositions/ differs from what this
                                  script would generate (CI runs this)

A composition is a recipe from ci/page-recipes.json promoted to a deliverable:
one folder holding a complete page.html with its copy slots still open, the
page.css a build would otherwise concatenate by hand, a manifest naming the
exact pattern versions inside, and a generated README. An agent building a
standard page fetches one folder instead of nine pattern folders.

Which recipes ship is decided in ci/page-recipes.json - a recipe carrying a
`composition` block ships, the rest stay validation fixtures - so the fixture
that must stay valid and the shell agents fetch are the same pattern list and
cannot drift apart. Everything under compositions/ comes out of this script;
nothing there is ever hand-edited. The freshness check mirrors the one
ci/lint.py runs on INDEX.md.

Exit code 0 = clean. Any finding prints `file: rule: detail` and exits 1;
a recipe that cannot be composed at all exits 2.
"""
import argparse
import json
import re
import shutil
import sys
import textwrap
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "compositions"
RECIPES = ROOT / "ci" / "page-recipes.json"

from check_page import (                                    # noqa: E402
    apply_variants, check_avoid_with, check_deprecated, check_ground_run,
    check_headings, check_known_page_type, check_one_per_page,
    check_opener_reserves_room, check_variant_choice, load, parse_recipe,
)

GENERATED_BY = "ci/compose.py - regenerate with: python ci/compose.py; never hand-edit"

# The slots a pattern carries, in the two forms the library defines: a content
# slot is an HTML comment, an attribute slot is a literal value.
COMMENT_SLOT = re.compile(r"<!--\s*slot\s*:\s*([\w-]+)\s*-->")
ATTR_SLOT = re.compile(r'([\w-]+)="slot:([\w-]+)"')
FURNITURE = re.compile(r"\{\{[^{}]+\}\}")

RULE = "=" * 64

# The head a served page needs. Every {{ }} value is a platform furniture
# token from the table in TOKENS.md, kept verbatim for the platform to fill -
# the same head scaffold ci/build_preview.py and ci/check_page.py write, with
# the preview-only stand-ins replaced by the real tokens.
PAGE = """<!-- {rule}
     {name}@{version} - generated by ci/compose.py from ci/page-recipes.json
     (library {library}). Never hand-edit: change the pattern or the recipe
     and regenerate with `python ci/compose.py`.

     How to use this shell:
       1. Write real copy into every slot. A content slot is an HTML comment,
          `slot: name`; an attribute slot is a literal `slot:name` value.
       2. Duplicate whatever block a pattern's own comments say to duplicate,
          one per real item - never invent content to fill a block.
       3. Strip every comment, this one included, in the same pass. A
          finished page contains no comment and no `slot:` anywhere.
       4. Keep every {{{{ }}}} token exactly as it stands, head and body: the
          platform fills them per brand and per page.
       5. page.css beside this file is the page's stylesheet - serve it, or
          merge it into the brand stylesheet unchanged.
     {rule} -->
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{{{pageTitle}}}}</title>
<meta name="description" content="{{{{metaDescription}}}}">
<meta name="keywords" content="{{{{metaKeywords}}}}">
<link rel="canonical" href="{{{{canonicalPage}}}}">
<link rel="icon" href="{{{{favicon}}}}">
<link rel="stylesheet" href="page.css">
</head>
<body>
{markup}
<!-- {rule}
     The site footer lands here. A footer pattern is on its way into
     this library; when it merges, regenerating compositions puts it
     in this spot. Until then leave nothing here - and strip this
     comment with the rest.
     {rule} -->
</body>
</html>
"""


def strip_tags(text):
    return re.sub(r"<[^>]+>", " ", text)


def find_slots(body):
    """Every slot in the markup, in document order, each named once."""
    found = []
    for m in re.finditer(r'([\w-]+)="slot:([\w-]+)"|<!--\s*slot\s*:\s*([\w-]+)\s*-->',
                         body):
        attr, attr_key, comment_key = m.groups()
        key = attr_key or comment_key
        entry = next((e for e in found if e["key"] == key), None)
        if entry is None:
            found.append({"key": key, "attrs": []})
            entry = found[-1]
        if attr:
            entry["attrs"].append(attr)
    return found


def slot_guidance(slot, sample):
    """One line saying what goes in the slot and roughly how long.

    Derived from the pattern's own preview sample - fake by design, but its
    shape and length are the shape and length the pattern was drawn for.
    """
    key, attrs = slot["key"], slot["attrs"]
    value = str(sample.get(key, ""))
    if attrs:
        where = "/".join(sorted(set(attrs)))
        if "src" in attrs:
            hint = "a path to real material"
        elif "alt" in attrs:
            hint = "what the image shows, in words"
        elif "id" in attrs or "aria-labelledby" in attrs:
            hint = "a page-unique id drawn from the heading"
        else:
            hint = "a short label, about %d word(s)" % max(len(value.split()), 1)
        return f"attribute ({where}): {hint}"
    if value.lstrip().startswith("<"):
        words = len(strip_tags(value).split())
        return f"markup shaped like the pattern's sample, about {words} words of copy"
    words = len(value.split())
    shown = value if len(value) <= 58 else value[:55] + "..."
    return f"text, about {words} word(s). Sample: {shown}"


def section_banner(item, mods, position, total):
    """The generated preface to one pattern's verbatim markup."""
    meta, sample = item["meta"], item["sample"]
    lines = [f"section {position} of {total} : {item['name']} v{meta.get('version', '?')}"]
    if mods:
        lines.append("variant: " + ", ".join(f"{k}={v}" for k, v in mods.items()))
    lines += textwrap.wrap(meta.get("description", ""), width=64)
    needs = meta.get("needs", "").strip()
    if needs and needs.lower() != "none":
        lines += textwrap.wrap("needs: " + needs, width=64)
    lines.append("slots:")
    for slot in find_slots(item["body"]):
        lines.append(f"  {slot['key']:<18} {slot_guidance(slot, sample)}")
    inner = "\n".join(f"     {line}".rstrip() for line in lines)
    return f"<!-- {RULE}\n{inner}\n     {RULE} -->"


def compose_body(item, mods):
    """The pattern's markup verbatim, less its metadata header, on the
    variant the recipe chose. Builder comments stay: they carry the
    duplicate-this-block instructions, and the consumer strips every
    comment in the pass that fills the slots, exactly as with a pattern
    fetched on its own."""
    body = re.sub(r"\s*<!--\n.*?\n-->", "", item["html"], count=1, flags=re.S)
    return apply_variants(item["name"], item["meta"], body.strip(), mods)


def page_checks(page, chosen, page_type):
    """The same page-level checks ci/check_page.py runs on a recipe."""
    failures = []
    for found in (
        check_known_page_type(page, page_type),
        check_deprecated(page),
        check_one_per_page(page),
        check_avoid_with(page),
        check_variant_choice(page, chosen),
        check_opener_reserves_room(page),
        check_headings(page),
    ):
        failures += found
    ground_bad, _ = check_ground_run(page, chosen)
    return failures + ground_bad


def compose_one(recipe, library):
    """One composition's files, as {filename: text}."""
    spec = recipe["composition"]
    name, version = spec["name"], spec["version"]
    parsed, err = parse_recipe(recipe["patterns"])
    if err:
        raise SystemExit(f"compositions/{name}@{version}: recipe: {err}")

    page, chosen = [], []
    for pattern_name, mods in parsed:
        item, err = load(pattern_name)
        if err:
            raise SystemExit(f"compositions/{name}@{version}: recipe: {err}")
        item["body"] = compose_body(item, mods)
        # Guidance is derived from the sample, so a slot without one is a
        # slot this script cannot describe - refuse rather than write a
        # shell that says nothing about what goes in it.
        for slot in find_slots(item["body"]):
            if slot["key"] not in item["sample"]:
                raise SystemExit(
                    f"compositions/{name}@{version}: {item['name']} slot "
                    f"{slot['key']!r} has no sample in preview-content.json")
        page.append(item)
        chosen.append(mods)

    bad = page_checks(page, chosen, recipe["page"])
    if bad:
        for line in bad:
            print(f"compositions/{name}@{version}: page-check: {line}")
        raise SystemExit(2)

    total = len(page)
    sections = []
    css = [f"/* {name}@{version} - generated by ci/compose.py (library "
           f"{library}). The patterns' CSS verbatim, in page order. Never "
           f"hand-edit: change the pattern and regenerate. */"]
    for position, (item, mods) in enumerate(zip(page, chosen), start=1):
        sections.append(section_banner(item, mods, position, total))
        sections.append(item["body"])
        css.append(f"/* ---- {item['name']} v{item['meta'].get('version', '?')} ---- */\n"
                   + item["css"].strip())

    html = PAGE.format(rule=RULE, name=name, version=version, library=library,
                       markup="\n\n".join(sections))

    # Every furniture token a pattern carries must reach the shell byte for
    # byte - these render on live sites, and a mangled one renders as text.
    for item in page:
        for token in FURNITURE.findall(item["body"]):
            if token not in html:
                raise SystemExit(
                    f"compositions/{name}@{version}: furniture token {token} "
                    f"from {item['name']} did not survive assembly")

    manifest = {
        "composition": name,
        "version": version,
        "page": recipe["page"],
        "library": library,
        "generated-by": GENERATED_BY,
        "patterns": [
            {"name": item["name"],
             "version": item["meta"].get("version", ""),
             **({"variant": mods} if mods else {})}
            for item, mods in zip(page, chosen)
        ],
    }

    readme = compose_readme(recipe, name, version, library, page, chosen)
    return {
        "page.html": html,
        "page.css": "\n\n".join(css) + "\n",
        "manifest.json": json.dumps(manifest, indent=2) + "\n",
        "README.md": readme,
    }


def compose_readme(recipe, name, version, library, page, chosen):
    lines = [
        f"# {name}@{version}",
        "",
        f"Generated by `ci/compose.py` from `ci/page-recipes.json` (library "
        f"{library}) - never hand-edit; change the source and regenerate.",
        "",
        f"A **{recipe['page']}** page shell. {recipe['why']}",
        "",
        "Fetch `page.html` and `page.css`, write real copy into the slots, "
        "duplicate whatever block a pattern's comments say to duplicate, "
        "strip every comment, and keep each `{{ }}` token exactly as found - "
        "the platform fills those. `page.css` is the whole stylesheet the "
        "page needs beyond the brand's tokens.",
        "",
        "## Sections, in order",
        "",
    ]
    for position, (item, mods) in enumerate(zip(page, chosen), start=1):
        variant = " (" + ", ".join(f"{k}={v}" for k, v in mods.items()) + ")" if mods else ""
        lines.append(f"{position}. **{item['name']}** "
                     f"v{item['meta'].get('version', '?')}{variant} - "
                     f"{item['meta'].get('description', '')}")
        for slot in find_slots(item["body"]):
            lines.append(f"   - `{slot['key']}` - {slot_guidance(slot, item['sample'])}")
    lines += [
        "",
        "The page ends where the site footer lands; a comment in `page.html` "
        "marks the spot for the footer pattern this library does not ship "
        "yet. Regenerating picks it up once it exists.",
        "",
        "## What is still yours to decide",
        "",
        "Copy, imagery and brand - never structure. The words in every slot "
        "are the brand's own; images are real material meeting each "
        "pattern's stated needs; the look comes from the brand's token "
        "values ([TOKENS.md](../../TOKENS.md)). The sections, their order "
        "and their markup are the composition - to change those, build from "
        "patterns directly instead.",
        "",
    ]
    return "\n".join(lines)


def compose_index(built, library):
    lines = [
        "# Compositions",
        "",
        "Pre-assembled page shells - generated by `ci/compose.py` from "
        "`ci/page-recipes.json` (library " + library + "), never hand-edited.",
        "Fetch one folder, write real copy into its slots, strip the "
        "comments, done - instead of assembling patterns by hand.",
        "",
    ]
    for folder, recipe in built:
        order = " -> ".join(recipe["patterns"])
        lines.append(f"- **{folder}** - {recipe['page']} - {order} - {recipe['why']}")
    return "\n".join(lines) + "\n"


def generate():
    """Everything under compositions/, as {relative path: text}."""
    recipes = json.loads(RECIPES.read_text(encoding="utf-8"))
    library = (ROOT / "LATEST").read_text(encoding="utf-8").strip()
    shipped = [r for r in recipes["recipes"] if "composition" in r]
    if not shipped:
        raise SystemExit("no recipe carries a composition block; nothing to generate")

    names = [f"{r['composition']['name']}@{r['composition']['version']}" for r in shipped]
    if len(set(names)) != len(names):
        raise SystemExit(f"composition names collide: {sorted(names)}")

    files, built = {}, []
    for recipe in shipped:
        folder = f"{recipe['composition']['name']}@{recipe['composition']['version']}"
        for filename, text in compose_one(recipe, library).items():
            files[f"{folder}/{filename}"] = text
        built.append((folder, recipe))
    files["README.md"] = compose_index(built, library)
    return files


def main():
    ap = argparse.ArgumentParser(
        description="Generate compositions/ from ci/page-recipes.json.")
    ap.add_argument("--check", action="store_true",
                    help="compare instead of writing; non-zero when stale")
    args = ap.parse_args()

    files = generate()

    if args.check:
        findings = []
        for rel, text in sorted(files.items()):
            path = OUT / rel
            held = path.read_text(encoding="utf-8") if path.is_file() else None
            if held != text:
                findings.append(f"compositions/{rel}: stale-composition: does "
                                f"not match the patterns and recipes; run ci/compose.py")
        if OUT.is_dir():
            for path in sorted(OUT.rglob("*")):
                rel = path.relative_to(OUT).as_posix()
                if path.is_file() and rel not in files:
                    findings.append(f"compositions/{rel}: stray-file: nothing "
                                    f"generates this; run ci/compose.py")
        if findings:
            print("\n".join(findings))
            print(f"\n{len(findings)} finding(s).")
            return 1
        print(f"clean: {len(files)} generated file(s) match compositions/.")
        return 0

    if OUT.exists():
        shutil.rmtree(OUT)
    for rel, text in sorted(files.items()):
        path = OUT / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
    folders = sorted({rel.split("/")[0] for rel in files if "/" in rel})
    print(f"wrote {len(files)} file(s): {', '.join(folders)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
